version: "3.8"
services:
    api:
        build:
            context: ./api
        ports:
            - "3000:3000"
        networks: 
            - app_network
    nginx:
        restart: always
        build:
            context: ./nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./front:/usr/share/nginx/html/static
        ports:
            - "80:80"
        networks: 
            - app_network

networks:
  app_network:
    driver: bridge